import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'


export default function Home() {
  const [resume, setResume] = useState({})
  const [theme, setTheme] = useState('dark')

  const Data = async () => {
    await fetch('/api/bryce-robinson')
      .then(response => response.json())
      .then(data => setResume(data))
      .then((err) => console.error(err))
  }

  
  const year =  new Date().getFullYear()
 


  useEffect(() => {
    Data()
    
  }, [])
  return (
    <div className={theme}>

      <Head>
        <title>{resume.name} {'|'} {resume.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" /></Script>

      </Head>
  
      <div>



        <article >
        <div >

<h1 id='name'>{resume.name}</h1>

<h2>{resume.title}</h2>
</div>

        <div id='contact-info' className='content'>
          <h3>Contact Info</h3>

<ul id='contact-info' aria-label='Contact Information'>
  <li>
    {resume.email}

  </li>
  <li>
    {resume["phone-number"]}

  </li>
  <li>
    {resume.address}

  </li>
  <li>
    {resume.linkedIn}

  </li>

</ul>


</div>
          <div id='summary' className='content'>
          <h3>
            Summary
          </h3>
          {resume.summary}


          </div>
          

            <div id='other-experience' className='content'>
              <h3>Other Professional Experience</h3>

              {resume.Other?.map((val, key) => {
                return (
                  <>
                    <h4>
                      {val.title}
                    </h4>{val.description}
                  </>
                )
              })}


            </div>

          <div className='content'>


            <h3>
              Work Experience
            </h3>

            {resume["work-experience"]?.map((val, key) => {
              return (
                <>
                  {val.company}
                  {val.description}
                  {val.dates}
                  <ul>
                    {val.description.map((val) => {
                      <li>{val}</li>
                    })}
                  </ul>


                </>

              )
            })}


          </div>
          <div id='tech-skills' className='content'>

          <h3>Technical Skills</h3>
          {resume.technicalSkills?.map((val, key) => {
            return (
              <>
                <h4>
                  {val.title}
                </h4>
                <ul className='flex-area'>
                  {val.skills.map((i) => {
                    return (
                      <>
                        <li className='boxed-item'>{i}</li>
                      </>
                    )
                  })}
                </ul>
              </>
            )
          })}


          </div>


          <div className='content'>

          <h3>Education</h3>
          {resume.Education?.map((val, key) => {
            return (
              <>
                <div>


                  {val.school}
                  {val.studies}
                  {val.dates}


                </div>
              </>
            )
          })}


          </div>









        </article>
        <footer>

          
          Made with React and Next JS <br/>

          copyright © {year} codebybryce

          


        </footer>
      </div>



    </div>
  )
}
